'use strict';
const $=s=>document.querySelector(s);let state=RosterStore.load();const today=()=>new Date().toLocaleDateString('sv-SE');const uuid=()=>crypto.randomUUID();const now=()=>new Date().toISOString();const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setAttendance(playerId,value){const date=today();const i=state.attendance.findIndex(x=>x.date===date&&x.playerId===playerId);const row={id:'attendance-'+date+'-'+playerId,type:'attendance',date,playerId,status:value?'present':'absent',updatedAt:now()};if(i<0)state.attendance.push(row);else state.attendance[i]=row;const p=state.players.find(x=>x.id===playerId);if(p){p.attendance=value?'true':'false';p.updatedAt=now()}save()}function save(){RosterStore.save(state);render()}
function render(){const q=$('#search').value.toLowerCase();const date=today();const attendance=new Map(state.attendance.filter(x=>x.date===date).map(x=>[x.playerId,x.status]));const list=state.players.filter(p=>[p.lastName,p.firstName,p.number,p.position,p.category].join(' ').toLowerCase().includes(q));$('#playerCount').textContent=state.players.length;$('#activeCount').textContent=state.players.filter(p=>p.status==='active').length;$('#u12Count').textContent=state.players.filter(p=>p.category==='U12').length;$('#u15Count').textContent=state.players.filter(p=>['U15','U18','Adult'].includes(p.category)).length;$('#playerGrid').innerHTML=list.length?list.map(p=>'<article class="player" data-id="'+esc(p.id)+'"><div class="number">'+esc(p.number||'—')+'</div><h3>'+esc(p.lastName)+' '+esc(p.firstName)+'</h3><p>'+esc(p.category)+' · '+esc(p.position||'POSITION 未設定')+'</p><p>'+esc(p.grade||'学年・年代 未設定')+'</p></article>').join(''):'<div class="empty">選手がまだ登録されていません。<br>「＋ 選手追加」から始められます。</div>';document.querySelectorAll('.player').forEach(x=>x.onclick=()=>openPlayer(x.dataset.id));document.querySelectorAll('[data-attendance]').forEach(x=>x.onchange=()=>setAttendance(x.dataset.attendance,x.checked));$('#teamTitle').textContent=state.team.name||'MY TEAM';$('#teamSummary').textContent=[state.team.category,state.team.season,state.team.philosophy].filter(Boolean).join(' · ')||'チーム情報を設定してください。';$('#recordSummary').textContent='Practice: '+state.records.filter(x=>x.type==='practice').length+' / Communication: '+state.records.filter(x=>x.type==='communication').length+' / Attendance days: '+new Set(state.attendance.map(x=>x.date)).size}
function openPlayer(id=''){const p=state.players.find(x=>x.id===id)||{id:'',number:'',status:'active',lastName:'',firstName:'',category:'U12',position:'',grade:'',dominantHand:'',memo:''};['number','status','lastName','firstName','category','position','grade','dominantHand','memo'].forEach(k=>$('#'+k).value=p[k]||'');$('#playerId').value=p.id;$('#deletePlayerBtn').hidden=!id;$('#playerDialog').showModal()}
$('#addPlayerBtn').onclick=()=>openPlayer();$('#search').oninput=render;$('#playerDialog .close').onclick=()=>$('#playerDialog').close();$('#teamDialog .close').onclick=()=>$('#teamDialog').close();
$('#playerForm').onsubmit=e=>{e.preventDefault();const id=$('#playerId').value||uuid();const p={id,number:$('#number').value.trim(),status:$('#status').value,lastName:$('#lastName').value.trim(),firstName:$('#firstName').value.trim(),category:$('#category').value,position:$('#position').value.trim(),grade:$('#grade').value.trim(),dominantHand:$('#dominantHand').value,memo:$('#memo').value.trim(),updatedAt:now()};const i=state.players.findIndex(x=>x.id===id);if(i<0)state.players.push(p);else state.players[i]=p;delete state.deletedPlayers[id];save();$('#playerDialog').close()};
$('#deletePlayerBtn').onclick=()=>{const id=$('#playerId').value;if(id&&confirm('この選手を削除しますか？')){state.players=state.players.filter(x=>x.id!==id);state.deletedPlayers[id]=now();save();$('#playerDialog').close()}};
$('#editTeamBtn').onclick=()=>{const t=state.team;$('#teamName').value=t.name;$('#teamCategory').value=t.category;$('#season').value=t.season;$('#teamPhilosophy').value=t.philosophy;$('#teamDialog').showModal()};
$('#teamForm').onsubmit=e=>{e.preventDefault();state.team={name:$('#teamName').value.trim(),category:$('#teamCategory').value.trim(),season:$('#season').value.trim(),philosophy:$('#teamPhilosophy').value.trim(),updatedAt:now()};save();$('#teamDialog').close()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');['roster','team','records','data'].forEach(v=>$('#'+v+'View').hidden=v!==b.dataset.view)});
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='zero-one-roster-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importBtn').onclick=()=>$('#importFile').click();$('#spoImportBtn').onclick=()=>$('#spoImportFile').click();$('#importFile').onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(!RosterStore.valid(v))throw new Error('ZERO ONE ROSTER形式ではありません');state=RosterStore.merge(state,v);save()}catch(err){alert(err.message)}e.target.value=''};
$('#spoImportFile').onchange=async e=>{try{const raw=JSON.parse(await e.target.files[0].text());const migrated=RosterMigration.fromSharePoint(raw);if(!migrated.players.length&&!migrated.records.length)throw new Error('profile_bb / practice_bb / communication_bb のデータを確認できませんでした');state=RosterStore.merge(state,migrated);save();alert('旧SPOデータを取り込みました。内容を確認してからOneDrive同期してください。')}catch(err){alert(err.message)}e.target.value=''};
async function initCloud(){try{const a=await RosterOneDrive.init();if(a)$('#syncStatus').textContent='OneDrive接続済み'}catch(e){$('#syncStatus').textContent=e.message}}
$('#connectBtn').onclick=async()=>{try{await RosterOneDrive.connect()}catch(e){alert(e.message)}};
$('#syncBtn').onclick=async()=>{try{$('#syncStatus').textContent='同期中…';if(!RosterOneDrive.isConnected())throw new Error('先にOneDriveへ接続してください');const cloud=await RosterOneDrive.read();if(cloud&&RosterStore.valid(cloud))state=RosterStore.merge(state,cloud);await RosterOneDrive.write(state);RosterStore.save(state);render();$('#syncStatus').textContent='同期完了'}catch(e){$('#syncStatus').textContent=e.message}};
render();initCloud();