'use strict';
const RosterOneDrive=(()=>{const CLIENT_ID='b75b499d-2b47-42ed-9e10-41cd76dbc6c5',SCOPES=['Files.ReadWrite.AppFolder'],GRAPH='https://graph.microsoft.com/v1.0';let client,account;
async function init(){client=new msal.PublicClientApplication({auth:{clientId:CLIENT_ID,authority:'https://login.microsoftonline.com/consumers',redirectUri:new URL('./',location.href).href},cache:{cacheLocation:'localStorage'}});await client.initialize();const r=await client.handleRedirectPromise();account=r?.account||client.getActiveAccount()||(client.getAllAccounts().length===1?client.getAllAccounts()[0]:null);if(account)client.setActiveAccount(account);return account}
async function connect(){await client.loginRedirect({scopes:SCOPES,prompt:'select_account'})}
async function request(path,options={},asText=false){if(!account)throw new Error('Microsoftアカウントへ接続してください');const token=(await client.acquireTokenSilent({account,scopes:SCOPES})).accessToken;const r=await fetch(GRAPH+path,{...options,headers:{...options.headers,Authorization:'Bearer '+token}});if(!r.ok){const e=new Error('OneDrive操作に失敗しました ('+r.status+')');e.status=r.status;throw e}return asText?r.text():r.status===204?null:r.json()}
async function folder(parent,name){const list=await request('/me/drive/items/'+parent+'/children');const found=list.value.find(x=>x.folder&&x.name.toLowerCase()===name.toLowerCase());if(found)return found;return request('/me/drive/items/'+parent+'/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})})}
async function target(){const root=await request('/me/drive/special/approot');return folder(root.id,'ROSTER')}
async function read(){const f=await target();try{const item=await request('/me/drive/items/'+f.id+':/roster.data');return JSON.parse(await request('/me/drive/items/'+item.id+'/content',{},true))}catch(e){if(e.status===404)return null;throw e}}
async function write(data){const f=await target();return request('/me/drive/items/'+f.id+':/roster.data:/content',{method:'PUT',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify(data)})}
return{init,connect,read,write,isConnected:()=>!!account};})();