'use strict';
const RosterOneDrive=(()=>{const CLIENT_ID='b75b499d-2b47-42ed-9e10-41cd76dbc6c5',SCOPES=['Files.ReadWrite.AppFolder'],GRAPH='https://graph.microsoft.com/v1.0';let client,account;
function msalApi(){return window.msal||null}
async function init(){const api=msalApi();if(!api?.PublicClientApplication)throw new Error('Microsoft接続機能を読み込めません。OneDrive接続時に再試行してください。');client=new api.PublicClientApplication({auth:{clientId:CLIENT_ID,authority:'https://login.microsoftonline.com/consumers',redirectUri:new URL('./',location.href).href,postLogoutRedirectUri:new URL('./',location.href).href},cache:{cacheLocation:'localStorage'},system:{allowPlatformBroker:false}});await client.initialize();const r=await client.handleRedirectPromise();const accounts=client.getAllAccounts();account=r?.account||client.getActiveAccount()||(accounts.length===1?accounts[0]:null);if(account)client.setActiveAccount(account);return account}
async function connect(){if(!client)await init();await client.loginRedirect({scopes:SCOPES,redirectUri:new URL('./',location.href).href,prompt:'select_account'})}
async function request(path,options={},asText=false){if(!account)throw new Error('Microsoftアカウントへ接続してください');const token=(await client.acquireTokenSilent({account,scopes:SCOPES})).accessToken;const r=await fetch(GRAPH+path,{...options,headers:{...options.headers,Authorization:'Bearer '+token}});if(!r.ok){const e=new Error('OneDrive操作に失敗しました ('+r.status+')');e.status=r.status;throw e}return asText?r.text():r.status===204?null:r.json()}
async function folder(parent,name){const list=await request('/me/drive/items/'+parent+'/children');const found=list.value.find(x=>x.folder&&x.name.toLowerCase()===name.toLowerCase());if(found)return found;return request('/me/drive/items/'+parent+'/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})})}
async function target(){const root=await request('/me/drive/special/approot');return folder(root.id,'ROSTER')}
async function read(){const f=await target();try{const item=await request('/me/drive/items/'+f.id+':/roster.data');return JSON.parse(await request('/me/drive/items/'+item.id+'/content',{},true))}catch(e){if(e.status===404)return null;throw e}}
async function photoFolder(){const root=await target();return folder(root.id,'photos')}
async function uploadPhoto(playerId,blob){const f=await photoFolder();return request('/me/drive/items/'+f.id+':/'+encodeURIComponent(playerId)+'.jpg:/content',{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:blob})}
async function uploadPhotoFromUrl(playerId,url){const response=await fetch(url,{credentials:'include'});if(!response.ok)throw new Error('旧写真取得 '+response.status);const blob=await response.blob();if(!blob.type.startsWith('image/'))throw new Error('画像形式ではありません');return uploadPhoto(playerId,blob)}
async function photoUrl(playerId){const f=await photoFolder();try{const item=await request('/me/drive/items/'+f.id+':/'+encodeURIComponent(playerId)+'.jpg');return item['@microsoft.graph.downloadUrl']||''}catch(e){if(e.status===404)return'';throw e}}
async function write(data){const f=await target();return request('/me/drive/items/'+f.id+':/roster.data:/content',{method:'PUT',headers:{'Content-Type':'application/json; charset=utf-8'},body:JSON.stringify(data)})}
return{init,connect,read,write,uploadPhoto,uploadPhotoFromUrl,photoUrl,isConnected:()=>!!account};})();