'use strict';
// Only explicitly confirmed aliases are converted; unknown schools are preserved.
const SCHOOL_ALIASES=Object.freeze({
  '大府西中':'大府市立大府西中学校',
  '大府西中学校':'大府市立大府西中学校',
  '大府市立西中学校':'大府市立大府西中学校',
  '大府市立大府西中学校':'大府市立大府西中学校'
});
function normalizeSchool(value){const name=String(value??'').trim();return Object.hasOwn(SCHOOL_ALIASES,name)?SCHOOL_ALIASES[name]:name}
function normalizeSchools(data){let changed=0;for(const player of data.players){const school=normalizeSchool(player.school||player.zaiseki||'');if(school!==String(player.school??'')){player.school=school;player.updatedAt=new Date().toISOString();changed++}}return changed}
const RosterStore=(()=>{const KEY='zero-one-roster-v1';const now=()=>new Date().toISOString();const empty=()=>({schema:'zero-one-roster',version:1,updatedAt:now(),team:{name:'',category:'',season:'',philosophy:'',updatedAt:now()},teams:[],players:[],records:[],attendance:[],activities:[],deletedPlayers:{}});const valid=v=>!!v&&v.schema==='zero-one-roster'&&v.version===1&&Array.isArray(v.players)&&Array.isArray(v.records);const normalize=v=>{const x=valid(v)?structuredClone(v):empty();x.deletedPlayers=x.deletedPlayers||{};x.attendance=Array.isArray(x.attendance)?x.attendance:[];x.activities=Array.isArray(x.activities)?x.activities:[];x.team=x.team||empty().team;x.teams=Array.isArray(x.teams)?x.teams:[];x.team.updatedAt=x.team.updatedAt||x.updatedAt||now();x.players=x.players.map(p=>({...p,updatedAt:p.updatedAt||x.updatedAt||now()}));return x};const load=()=>{try{const data=normalize(JSON.parse(localStorage.getItem(KEY)||'null'));if(normalizeSchools(data))save(data);return data}catch{return empty()}};const save=v=>{normalizeSchools(v);v.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(v));return v};const newer=(a,b)=>Date.parse(a||0)>=Date.parse(b||0);const merge=(local,cloud)=>{const a=normalize(local),b=normalize(cloud),out=empty();out.team=newer(a.team.updatedAt,b.team.updatedAt)?a.team:b.team;const teams=new Map();for(const t of [...b.teams,...a.teams]){const key=String(t.id||t.name);const old=teams.get(key);if(!old||newer(t.updatedAt,old.updatedAt))teams.set(key,t)}out.teams=[...teams.values()];out.deletedPlayers={...b.deletedPlayers,...a.deletedPlayers};for(const [id,t] of Object.entries(b.deletedPlayers))if(!out.deletedPlayers[id]||newer(t,out.deletedPlayers[id]))out.deletedPlayers[id]=t;const map=new Map();for(const p of [...b.players,...a.players]){const old=map.get(p.id);if(!old||newer(p.updatedAt,old.updatedAt))map.set(p.id,p)}out.players=[...map.values()].filter(p=>!out.deletedPlayers[p.id]||newer(p.updatedAt,out.deletedPlayers[p.id]));const rec=new Map();for(const r of [...b.records,...a.records]){const id=r.id||JSON.stringify(r);const old=rec.get(id);if(!old||newer(r.updatedAt,old.updatedAt))rec.set(id,r)}out.records=[...rec.values()];const att=new Map();for(const r of [...b.attendance,...a.attendance]){const key=JSON.stringify([r.teamId||'',r.date,r.playerId]);const old=att.get(key);if(!old||newer(r.updatedAt,old.updatedAt))att.set(key,r)}out.attendance=[...att.values()];const acts=new Map();for(const r of [...b.activities,...a.activities]){const key=JSON.stringify([r.teamId||'',r.date]);const old=acts.get(key);if(!old||newer(r.updatedAt,old.updatedAt))acts.set(key,r)}out.activities=[...acts.values()];normalizeSchools(out);out.updatedAt=now();return out};return{empty,valid,normalize,normalizeSchool,normalizeSchools,load,save,merge};})();