const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{if(localStorage.getItem('comments-seed'))return;localStorage.setItem('comments-seed','1');localStorage.setItem('zero-one-roster-v1',JSON.stringify({schema:'zero-one-roster',version:1,teams:[{id:'a',name:'A'},{id:'b',name:'B'}],players:[{id:'p',lastName:'選手',firstName:'一',teamId:'a',position:'PG'},{id:'q',lastName:'選手',firstName:'二',teamId:'b'}],records:[]}))});
await page.goto(process.env.ROSTER_URL||'http://127.0.0.1:8765');await page.waitForFunction(()=>document.querySelector('#addTeamCommentBtn')?.onclick);assert.equal(await page.locator('#appVersion').textContent(),'v0.1.36');
await page.click('#addTeamCommentBtn');assert.equal(await page.inputValue('#commentTeam'),'');await page.selectOption('#commentTeam','a');await page.fill('#commentText','全員で声を出せた');await page.click('#commentForm [type=submit]');
await page.click('[data-player-comment="p"]');assert.equal(await page.inputValue('#commentTeam'),'a');await page.fill('#commentText','<b>良いパス</b>');await page.evaluate(()=>render());assert.equal(await page.inputValue('#commentText'),'<b>良いパス</b>');await page.click('#commentForm [type=submit]');assert.equal(await page.locator('#playerDialog').isVisible(),false);assert.equal(await page.locator('.playerComment b').count(),0);assert.equal(await page.evaluate(()=>state.players[0].position),'PG');
await page.click('#nextDate');assert.equal(await page.locator('.playerComment p').count(),0);await page.click('#prevDate');assert.equal(await page.locator('.playerComment p').count(),1);
await page.selectOption('#activeTeam','b');assert.equal(await page.locator('#teamCommentList .practiceRecord').count(),0);await page.click('#addTeamCommentBtn');await page.fill('#commentText','Bの練習');await page.click('#commentForm [type=submit]');await page.selectOption('#activeTeam','');await page.reload();assert.equal(await page.locator('#teamCommentList .practiceRecord').count(),2);
await page.click('[data-view="records"]');assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),3);await page.locator('#commentHistoryList .practiceRecord').filter({hasText:'選手 一'}).locator('button').click();await page.fill('#commentText','次も続けよう');await page.click('#commentForm [type=submit]');assert.equal(await page.evaluate(()=>state.records.length),3);
await page.click('[data-view="roster"]');await page.click('[data-player-comment="p"]');await page.fill('#commentText','');await page.click('#commentForm [type=submit]');await page.reload();assert.equal(await page.locator('.playerComment p').count(),0);assert.equal(await page.evaluate(()=>state.records.filter(r=>r.deleted).length),1);
await page.evaluate(()=>{globalThis.commentWrites=[];RosterOneDrive.isConnected=()=>true;RosterOneDrive.photoUrl=async()=>'';RosterOneDrive.write=async d=>commentWrites.push(structuredClone(d))});await page.click('[data-player-comment="q"]');await page.fill('#commentText','守備が良かった');await page.click('#commentForm [type=submit]');await page.waitForFunction(()=>commentWrites.some(d=>d.records.some(r=>r.text==='守備が良かった')));
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
if(!process.env.ROSTER_URL){require('node:fs').mkdirSync('reports/comments',{recursive:true});const icon=await browser.newPage({viewport:{width:512,height:512},deviceScaleFactor:1});await icon.goto('http://127.0.0.1:8765/icons/roster.svg');await icon.screenshot({path:'reports/comments/roster-512.png',omitBackground:true});await icon.setViewportSize({width:192,height:192});await icon.screenshot({path:'reports/comments/roster-192.png',omitBackground:true});await page.screenshot({path:'reports/comments/mobile.png',fullPage:true})}
console.log('PASS: mobile daily team/player notes, escaping, draft retention on render, date/team isolation, history editing, deletion, reload and mocked OneDrive write');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
