const {chromium}=require('playwright'),assert=require('node:assert/strict'),X=require('../vendor/xlsx.full.min.js');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(localStorage.getItem('jba-test'))return;localStorage.setItem('jba-test','yes');localStorage.setItem('zero-one-roster-v1',JSON.stringify({schema:'zero-one-roster',version:1,teams:[{id:'a',name:'A'}],players:[{id:'p1',jbaId:'123',lastName:'確認',firstName:'一',position:'PG',gender:'女',birthday:'2010-01-01',number:'7',status:'inactive',category:'U15',memo:'保持',dominantHand:'右',roster:'D',teamId:'a',teamName:'A',teamAssignmentManual:true},{id:'p2',lastName:'確認',firstName:'二',position:'C',gender:'男',status:'active'}],records:[{id:'history',note:'保持'}]}))});
 await page.goto(process.env.ROSTER_URL||'http://127.0.0.1:8765');await page.waitForFunction(()=>document.querySelector('#jbaImportFile')?.onchange);assert.equal(await page.locator('#appVersion').textContent(),'v0.1.32');assert.match(await page.locator('#excelStatus').textContent(),/準備OK/);
 const rows=[{'メンバーID':'１２３.0','氏名':'確認 一','ポジション':'','性別':'男性','生年月日':'2012年6月28日','ユニフォーム番号':'','カテゴリー':'','チームID':'b','チーム名':'B'},{'メンバーID':'456','氏名':'確認二','生年月日':'2013年8月9日','性別':'','ポジション':''}];
 const wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.json_to_sheet(rows),'JBA');
 await page.click('[data-view="data"]');await page.locator('#jbaImportFile').setInputFiles({name:'JBA.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(X.write(wb,{type:'buffer',bookType:'xlsx'}))});await page.waitForFunction(()=>state.players[0].birthday==='2012-06-28');assert.match(await page.locator('#jbaImportResult').textContent(),/新規 0 \/ 更新 2/);
 const p=await page.evaluate(()=>state.players[0]);assert.equal(p.position,'PG');assert.equal(p.gender,'男');assert.equal(p.status,'inactive');assert.equal(p.number,'7');assert.equal(p.memo,'保持');assert.equal(p.dominantHand,'右');assert.equal(p.teamId,'a');assert.equal(await page.evaluate(()=>state.players[1].birthday),'2013-08-09');assert.equal(await page.evaluate(()=>state.players[1].position),'C');
 await page.click('[data-view="roster"]');await page.selectOption('#filterStatus','');await page.locator('[data-id="p1"]').locator('h3').click();assert.equal(await page.inputValue('#birthday'),'2012-06-28');assert.equal(await page.inputValue('#gender'),'男');assert.equal(await page.inputValue('#position'),'PG');await page.click('#savePlayerBtn');
 await page.click('[data-view="data"]');const json={format:'zero-one-roster-jba-import',rows:[{'メンバーID':'123','生年月日':'不正','性別':'','ポジション':''}]};await page.locator('#jbaJsonImportFile').setInputFiles({name:'jba.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(json))});await page.waitForFunction(()=>document.querySelector('#jbaImportResult').textContent.includes('形式を確認'));assert.equal(await page.evaluate(()=>state.players[0].birthday),'2012-06-28');
 const conflict=await page.evaluate(()=>importJbaRows([{'メンバーID':'789','氏名':'違う 一'},{'メンバーID':'789','氏名':'違う 二'}]));assert.equal(conflict.skipped,2);assert.equal(await page.evaluate(()=>state.players.length),2);
 await page.reload();assert.equal(await page.evaluate(()=>state.players[0].position),'PG');assert.equal(await page.evaluate(()=>state.players[0].gender),'男');assert.equal(await page.evaluate(()=>state.records[0].note),'保持');assert.deepEqual(errors,[]);console.log('PASS: real XLSX and JSON inputs, empty values retained, Japanese birth date/gender applied, name fallback without duplicates, editor persistence, invalid rows reported, duplicate IDs held');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
