const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{webcrypto}=require('crypto');const c={crypto:webcrypto,Date};vm.createContext(c);vm.runInContext(fs.readFileSync('jba.js','utf8')+';globalThis.J=RosterJba',c);const J=c.J;
const old={id:'keep-id',jbaId:'123',lastName:'確認',firstName:'選手',position:'PG',gender:'女',birthday:'2010-01-01',number:'7',category:'U15',status:'inactive',dominantHand:'右',memo:'メモ',roster:'D',teamId:'manual',teamName:'手動チーム',teamAssignmentManual:true,development:{defense:'保持'},photoVersion:3,jbaSource:{coachLicense:'保持'}};
const blank=J.parse({'メンバーID':'１２３.0','氏名':'確認　選手','ポジション':'　','性別':'','身長':null});assert.equal(J.match([old],blank).player.id,'keep-id');const kept=J.merge(old,blank);for(const key of ['position','gender','birthday','number','category','status','dominantHand','memo','roster','teamId','photoVersion'])assert.equal(kept[key],old[key]);assert.equal(kept.development.defense,'保持');assert.equal(kept.jbaSource.coachLicense,'保持');
const filled=J.merge(old,J.parse({'メンバーID':'123','生年月日':'2012年6月28日','性別':'男性','チームID':'external','チーム名':'外部','身長':0}));assert.equal(filled.birthday,'2012-06-28');assert.equal(filled.gender,'男');assert.equal(filled.position,'PG');assert.equal(filled.height,'0');assert.equal(filled.teamId,'manual');assert.equal(filled.jbaSource.teamId,'external');
const invalid=J.parse({'生年月日':'2012年2月30日','性別':'未回答'});assert.equal(invalid.warnings.length,2);assert.equal(J.merge(old,invalid).birthday,old.birthday);assert.equal(J.merge(old,invalid).gender,'女');
assert.equal(J.birthday(1),'1900-01-01');assert.equal(J.birthday(60),'');assert.equal(J.birthday(61),'1900-03-01');assert.equal(J.birthday(1,{date1904:true}),'1904-01-02');assert.equal(J.birthday('２０１２年６月２８日'),'2012-06-28');assert.equal(J.birthday('2012-06-28T23:00:00-09:00'),'2012-06-28');
const unlinked={...old,jbaId:''};assert.equal(J.match([unlinked],J.parse({'メンバーID':'456','氏名':'確認選手','生年月日':'2012年6月28日'})).player.id,old.id);assert.match(J.match([old],J.parse({'メンバーID':'456','氏名':'確認選手'})).reason,/異なり/);assert(J.match([old,{...old,id:'other'}],blank).reason);
const newP=J.merge(null,J.parse({'氏名':'新規 選手'}));assert.equal(newP.status,'active');assert.equal(newP.category,'Other');assert(newP.id);
console.log('PASS: nonempty-only merge, local fields retained, normalized ID/name match, date/gender conversion, invalid-value retention, Excel date systems and conflicting IDs');
