const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..'),site=process.env.SITE_URL;
if(site&&site!=='https://yuge-u.github.io/zero-one-roster/')throw new Error('Unexpected public URL');
const server=http.createServer((req,res)=>{
  const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname==='/'?'/index.html':new URL(req.url,'http://local').pathname));
  if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}
  fs.readFile(file,(err,body)=>{if(err){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'})[path.extname(file)]||'application/octet-stream');res.end(body)});
});
const fixture={schema:'zero-one-roster',version:1,updatedAt:'2024-02-29T00:00:00Z',team:{name:'共通プロフィール',updatedAt:'2024-02-29T00:00:00Z'},teams:[{id:'a',name:'現在のチームＡ'},{id:'b',name:'チームB'}],players:[{id:'p1',lastName:'山田',firstName:'太郎',nameKana:'ヤマダ タロウ',teamId:'b',status:'active',position:'PG'},{id:'p2',lastName:'佐藤',firstName:'花子',nameKana:'サトウ ハナコ',teamId:'b',status:'active'}],records:[
  {id:'practice-comment:'+JSON.stringify(['2024-02-29','a','p1']),type:'practice-comment',date:'2024-02-29',teamId:'a',teamName:'旧チームＡ',playerId:'p1',playerName:'山田 太郎',text:'<b>良いパス</b>',updatedAt:'2024-02-29T00:00:00Z'},
  {id:'practice-comment:'+JSON.stringify(['2024-02-29','b','p2']),type:'practice-comment',date:'2024-02-29',teamId:'b',playerId:'p2',text:'Bのコメント',updatedAt:'2024-02-29T00:00:00Z'},
  {id:'practice-comment:'+JSON.stringify(['2024-03-01','a','p1']),type:'practice-comment',date:'2024-03-01',teamId:'a',playerId:'p1',text:'翌月のコメント',updatedAt:'2024-03-01T00:00:00Z'},
  {id:'practice-comment:'+JSON.stringify(['2023-12-31','a','p1']),type:'practice-comment',date:'2023-12-31',teamId:'a',playerId:'p1',text:'前年のコメント',updatedAt:'2023-12-31T00:00:00Z'},
  {id:'removed',type:'practice-comment',date:'2024-02-29',teamId:'a',text:'削除した記録',deleted:true,updatedAt:'2024-02-29T00:00:00Z'},
  {id:'practice1',type:'practice-session',date:'2024-02-29',teamId:'a',teamName:'旧チームＡ',plan:{id:'plan1',revision:'revision1',hash:'synthetic',title:'固定した練習',team:'U15',goal:'パス',totalMinutes:10,items:[{id:'item1',name:'パス練習',minutes:10}]},items:[{id:'item1',name:'パス練習',minutes:10,actualMinutes:12}],note:'元のメモ',updatedAt:'2024-02-29T00:00:00Z'},
  {id:'legacy',type:'communication',date:'2024/02/28',playerName:'退団した選手',note:'<script>旧記録</script>',updatedAt:'2024-02-28T00:00:00Z'},
  {id:'undated',type:'practice',menu:'日付なしの旧メニュー',updatedAt:'2024-02-29T00:00:00Z'}
],activities:[{id:'a29',date:'2024-02-29',teamId:'a',name:'Aの練習',note:'Aの会場'},{id:'b29',date:'2024-02-29',teamId:'b',name:'Bの大会',note:'Bの会場'},{id:'a31',date:'2024-03-01',teamId:'a',name:'翌月の試合'},{id:'future',date:'2025-01-01',teamId:'a',name:'翌年の予定'}],attendance:[{id:'p1a',date:'2024-02-29',teamId:'a',playerId:'p1',status:'present'},{id:'p2b',date:'2024-02-29',teamId:'b',playerId:'p2',status:'absent'},{id:'former',date:'2024-02-29',teamId:'a',playerId:'deleted-player',playerName:'退団した選手',status:'present'},{id:'p1old',date:'2024-02-28',teamId:'a',playerId:'p1',status:'absent'}],deletedPlayers:{'deleted-player':'2024-02-01T00:00:00Z'}};
const results=[];
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=site||'http://127.0.0.1:'+server.address().port+'/';
  for(const [engineName,engine] of Object.entries({chromium,webkit}))for(const config of [{name:'desktop',viewport:{width:1280,height:850},deviceScaleFactor:2},{name:'touch',viewport:{width:320,height:740},deviceScaleFactor:3,isMobile:true,hasTouch:true}]){
    const browser=await engine.launch();try{
      const context=await browser.newContext(config),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
      await page.route('**/*',route=>new URL(route.request().url()).origin===new URL(url).origin?route.continue():route.abort());
      await page.addInitScript(data=>{if(!localStorage.getItem('calendar-seeded')){localStorage.setItem('zero-one-roster-v1',JSON.stringify(data));localStorage.setItem('calendar-seeded','yes');localStorage.setItem('synthetic-msal-marker','account-cache-preserved');sessionStorage.setItem('synthetic-msal-session','redirect-state-preserved')}},fixture);
      const check=(id,description)=>{results.push({engine:engineName,config:config.name,id,description});console.log('PASS',engineName,config.name,id,description)};
      await page.goto(url);await page.waitForFunction(()=>document.querySelector('#addTeamCommentBtn')?.onclick&&document.querySelector('#recordDate')?.onchange);
      await page.waitForFunction(()=>getComputedStyle(document.querySelector('.zeroone-splash')).visibility==='hidden');assert.equal(await page.locator('#appVersion').textContent(),'v0.1.37');await page.fill('#attendanceDate','2024-02-29');await page.locator('#attendanceDate').dispatchEvent('change');
      await page.evaluate(()=>{globalThis.calendarCloudWrites=0;RosterOneDrive.write=async()=>{calendarCloudWrites++}});
      const original=await page.evaluate(()=>({local:localStorage.getItem('zero-one-roster-v1'),date:activeDate(),team:activeTeam}));
      await page.click('[data-view="records"]');assert.equal(await page.inputValue('#recordDate'),'2024-02-29');assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),2);assert.equal(await page.locator('#practiceHistoryList .practiceRecord').count(),1);assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 8件/);check('T01','selected roster day initializes records and hides other dates/deletions');
      assert.equal(await page.locator('#recordCalendar [data-record-date]').count(),29);assert.equal(await page.locator('[data-record-date="2024-02-29"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#commentHistoryList p b').count(),0);assert.equal(await page.locator('#recordsView').getByText('削除した記録',{exact:true}).count(),0);check('T02','leap-day calendar, selected-day semantics and escaped text');
      const rows=page.locator('#activityHistory .historyRow');assert.equal(await rows.count(),2);const aRow=rows.filter({hasText:'現在のチームＡ'}),bRow=rows.filter({hasText:'チームB'});assert.match(await aRow.innerText(),/山田 太郎（出席）/);assert.match(await aRow.innerText(),/退団した選手（出席）/);assert.doesNotMatch(await aRow.innerText(),/佐藤|Bの大会/);assert.match(await bRow.innerText(),/佐藤 花子（欠席）/);assert.doesNotMatch(await bRow.innerText(),/山田|Aの練習/);check('T03','same-day teams, moved player, absent player and deleted-player snapshot stay separate');
      await page.selectOption('#recordTeam','a');assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),1);assert.equal(await rows.count(),1);assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 5件/);assert.match(await page.locator('[data-record-date="2024-02-29"]').getAttribute('aria-label'),/記録5件/);check('T04','team selector filters all history types and calendar counts');
      await page.fill('#recordSearch','山田　太郎');assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),1);assert.equal(await page.locator('#practiceHistoryList .practiceRecord').count(),0);assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 2件/);await page.fill('#recordSearch','ﾔﾏﾀﾞﾀﾛｳ');assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 2件/);check('T05','spaced/full-width player name and half-width kana search');
      await page.selectOption('#recordTeam','');await page.fill('#recordSearch','現在のチームa 山田');assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 2件/);await page.fill('#recordSearch','旧チームa');assert.equal(await page.locator('#practiceHistoryList .practiceRecord').count(),1);assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),1);check('T06','current and historical team labels plus AND search');
      await page.fill('#recordSearch','該当しない名前');assert(await page.locator('#recordEmpty').isVisible());assert.equal(await page.locator('#activityHistory .historyRow').count(),0);await page.click('#recordClear');assert.equal(await page.inputValue('#recordSearch'),'');assert.equal(await page.inputValue('#recordTeam'),'');check('T07','no-match state and clear preserve the period');
      await page.click('[data-record-mode="year"]');assert.equal(await page.locator('#recordCalendar [data-record-month]').count(),12);assert(await page.locator('#recordWeek').isHidden());assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 12件/);await page.click('[data-record-month="2024-02"]');assert.equal(await page.locator('[data-record-mode="month"]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 10件/);await page.click('[data-record-date="2024-02-29"]');assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 8件/);check('T08','year→month→day drill-down and exact counts');
      await page.click('#recordNext');assert.equal(await page.inputValue('#recordDate'),'2024-03-01');assert.equal(await page.locator('#commentHistoryList .practiceRecord').count(),1);assert.match(await page.locator('#commentHistoryList').innerText(),/翌月のコメント/);await page.click('#recordPrev');assert.equal(await page.inputValue('#recordDate'),'2024-02-29');check('T09','day navigation crosses leap-month boundary');
      await page.click('[data-record-mode="month"]');await page.click('#recordPrev');assert.equal(await page.inputValue('#recordMonth'),'2024-01');assert(await page.locator('#recordEmpty').isVisible());await page.click('#recordNext');assert.equal(await page.inputValue('#recordMonth'),'2024-02');await page.click('[data-record-mode="year"]');await page.click('#recordPrev');assert.equal(await page.inputValue('#recordYear'),'2023');assert.match(await page.locator('#commentHistoryList').innerText(),/前年のコメント/);await page.click('#recordNext');check('T10','month/year navigation and prior-year records');
      await page.fill('#recordYear','2025');await page.locator('#recordYear').dispatchEvent('change');assert.match(await page.locator('#activityHistory').innerText(),/翌年の予定/);await page.click('[data-record-mode="month"]');await page.fill('#recordMonth','2024-02');await page.locator('#recordMonth').dispatchEvent('change');await page.click('[data-record-mode="day"]');await page.fill('#recordDate','2024-02-28');await page.locator('#recordDate').dispatchEvent('change');assert.match(await page.locator('#recordOtherList').innerText(),/退団した選手/);assert.equal(await page.locator('#recordOtherList script').count(),0);await page.fill('#recordSearch','退団した選手');assert.match(await page.locator('#recordResultsLabel').innerText(),/記録 1件/);check('T11','direct period inputs, future activity, legacy explicit date and retired-name search');
      await page.click('#recordClear');await page.click('#recordToday');assert.equal(await page.inputValue('#recordDate'),await page.evaluate(()=>today()));await page.fill('#recordDate','2024-02-29');await page.locator('#recordDate').dispatchEvent('change');await page.selectOption('#recordTeam','b');await page.click('[data-view="roster"]');assert.equal(await page.inputValue('#attendanceDate'),original.date);assert.equal(await page.inputValue('#activeTeam'),original.team);await page.click('[data-view="records"]');assert.equal(await page.inputValue('#recordTeam'),'b');check('T12','today and records filters stay independent from roster and survive tab switching');
      assert.equal(await page.evaluate(()=>localStorage.getItem('zero-one-roster-v1')),original.local);assert.equal(await page.evaluate(()=>calendarCloudWrites),0);assert.equal(await page.evaluate(()=>localStorage.getItem('synthetic-msal-marker')),'account-cache-preserved');assert.equal(await page.evaluate(()=>sessionStorage.getItem('synthetic-msal-session')),'redirect-state-preserved');check('T13','read-only browsing preserves saved bytes and synthetic auth with no cloud writes');
      await page.click('#recordClear');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert((await page.locator('[data-record-date="2024-02-29"]').boundingBox()).height>=44);await page.locator('[data-record-mode="month"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[data-record-mode="month"]').getAttribute('aria-pressed'),'true');await page.click('[data-record-mode="day"]');check('T14','320px/desktop fit, touch target and keyboard controls');
      fs.mkdirSync(path.join(root,'reports','records-calendar'),{recursive:true});await page.screenshot({path:path.join(root,'reports','records-calendar',engineName+'-'+config.name+'-day.png'),fullPage:true});await page.click('[data-record-mode="year"]');await page.screenshot({path:path.join(root,'reports','records-calendar',engineName+'-'+config.name+'-year.png'),fullPage:true});await page.click('[data-record-mode="day"]');
      await page.locator('#activityHistory [data-history-team="a"]').click();assert(await page.locator('#rosterView').isVisible());assert.equal(await page.inputValue('#attendanceDate'),'2024-02-29');assert.equal(await page.inputValue('#activeTeam'),'a');await page.click('[data-view="records"]');assert(await page.locator('.teamContext').isHidden());assert.equal(await page.inputValue('#recordTeam'),'');check('T18','existing history→roster action opens the matching day/team without changing records filters');
      await page.locator('#commentHistoryList .practiceRecord').filter({hasText:'山田 太郎'}).locator('[data-edit-comment]').click();assert.match(await page.locator('#commentContext').innerText(),/2024-02-29/);await page.fill('#commentText','履歴からの編集');await page.click('#commentForm [type=submit]');assert.equal(await page.evaluate(()=>state.records.length),fixture.records.length);assert.equal(await page.evaluate(()=>state.players[0].position),'PG');assert.equal(await page.evaluate(()=>state.records.find(r=>r.type==='practice-comment'&&r.date==='2024-02-29'&&r.teamId==='a').teamId),'a');assert.match(await page.locator('#commentHistoryList').innerText(),/履歴からの編集/);check('T15','existing comment editor retains IDs, historical team and player profile');
      await page.locator('#practiceHistoryList [data-edit-practice="practice1"]').click();assert.equal(await page.inputValue('#practicePlan'),'revision1');await page.fill('#practiceNote','練習履歴から編集');await page.locator('#practiceForm button[type=submit]').click();assert.equal(await page.evaluate(()=>state.records.find(r=>r.id==='practice1').plan.title),'固定した練習');assert.match(await page.locator('#practiceHistoryList').innerText(),/練習履歴から編集/);check('T16','existing practice editor preserves pinned snapshot and record ID');
      await page.reload();await page.click('[data-view="records"]');await page.fill('#recordDate','2024-02-29');await page.locator('#recordDate').dispatchEvent('change');assert.match(await page.locator('#commentHistoryList').innerText(),/履歴からの編集/);assert.match(await page.locator('#practiceHistoryList').innerText(),/練習履歴から編集/);assert.equal(await page.evaluate(()=>state.records.find(r=>r.id==='removed').deleted),true);assert.equal(await page.evaluate(()=>state.records.find(r=>r.id==='undated').date),undefined);assert.equal(await page.evaluate(()=>state.deletedPlayers['deleted-player']),'2024-02-01T00:00:00Z');assert.equal(await page.evaluate(()=>localStorage.getItem('synthetic-msal-marker')),'account-cache-preserved');check('T17','reload retains edited records, undated data, tombstones and synthetic auth');
      assert.deepEqual(errors,[]);await context.close();
    }finally{await browser.close()}
  }
  fs.writeFileSync(path.join(root,'reports','records-calendar','results.json'),JSON.stringify({version:'v0.1.37',url:site||'local',cases:results.length,results},null,2));assert.equal(results.length,72);
})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>server.close());
